set nocompatible
set number
syntax enable
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set showcmd
set cursorline
filetype indent on
set showmatch
set incsearch
set hlsearch
" setting the max line length to 80
"set tw=80
set colorcolumn=80

" EXPERIMENT
filetype plugin on
" search down into subfolders (tab to autocomplete)
set path+=**
set wildmenu


command PP !python3 %

" comments colour fix
:set background=light
:colorscheme blue
