#! /usr/bin/bash

<<'###INTRO'                                                                       
This script starts the Localstack container.
###INTRO

LOCALSTACK_DIR="/home/vagrant/bin/localstack"

echo "Starting the Localstack Docker container defined in $LOCALSTACK_DIR..."
cd $LOCALSTACK_DIR
docker compose up -d
echo "To see the logs, use the following command:"
echo log

